// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOw4TGBsKBOAKr9vUI2Dcrode9WEQyjGc',
    appId: '1:56609226626:web:846f6a11ca36b6ff73d99b',
    messagingSenderId: '56609226626',
    projectId: 'cw-8-e8fff',
    authDomain: 'cw-8-e8fff.firebaseapp.com',
    storageBucket: 'cw-8-e8fff.firebasestorage.app',
    measurementId: 'G-XKQT6YN5MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxzKDF0mkxJLvCm4aep3iKgSfwJQGhTk',
    appId: '1:56609226626:android:977a8f8a20d8edce73d99b',
    messagingSenderId: '56609226626',
    projectId: 'cw-8-e8fff',
    storageBucket: 'cw-8-e8fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0U-3htzjB0Sv9YDBKu_WCpbpdVve5qRU',
    appId: '1:56609226626:ios:347db37d04ebab6e73d99b',
    messagingSenderId: '56609226626',
    projectId: 'cw-8-e8fff',
    storageBucket: 'cw-8-e8fff.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0U-3htzjB0Sv9YDBKu_WCpbpdVve5qRU',
    appId: '1:56609226626:ios:347db37d04ebab6e73d99b',
    messagingSenderId: '56609226626',
    projectId: 'cw-8-e8fff',
    storageBucket: 'cw-8-e8fff.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOw4TGBsKBOAKr9vUI2Dcrode9WEQyjGc',
    appId: '1:56609226626:web:9a26988012ab7cb473d99b',
    messagingSenderId: '56609226626',
    projectId: 'cw-8-e8fff',
    authDomain: 'cw-8-e8fff.firebaseapp.com',
    storageBucket: 'cw-8-e8fff.firebasestorage.app',
    measurementId: 'G-GEV4WKFB09',
  );
}
